add error output if wal fails

diff --git a/wp b/wp
--- a/wp
+++ b/wp
@@ -1,6 +1,6 @@
 #!/usr/bin/env bash
 
-VERSION="1.1.2"
+VERSION="1.1.3"
 
 # wp: a wrapper script mostly for pywal and fetch oneliners
 # Note - most wallpaper-changing functions are mac-specific (for now)
@@ -41,15 +41,19 @@ _run_wal () {
     if [[ ! -f "$1" ]]; then exit 1; fi
 
     if ! command -v wal > /dev/null; then
-        echo "This functionality requires 'wal' (pywal) provided by pip."
-        echo "Make sure 'wal' is installed and in your PATH."
+        echo "This functionality requires 'wal' (pywal) provided by pip." >&2
+        echo "Make sure 'wal' is installed and in your PATH." >&2
         exit 2
     fi
 
     # -s skip changing colors
     # -n skip reloading wallpaper
     # -i input file
-    wal -sn -i "$1"
+    if ! wal -sn -i "$1"; then
+        echo "Running 'wal' failed. Check the output of:" >&2
+        echo "wal -sn -i $1" >&2
+        exit 2
+    fi
 
     cp "$1" "${ROOT}/wp"
 }
@@ -133,7 +137,7 @@ change_wallpaper () {
     if [[ ! -f "$file" ]]; then exit 1; fi
 
     if [[ $dry -eq 0 ]]; then
-        (_run_wal "$file" && _cache "$(_space_id)" "$file") >/dev/null 2>&1 &
+        (_run_wal "$file" && _cache "$(_space_id)" "$file") >/dev/null &
     fi
     osascript -e "tell application \"System Events\" to tell desktop $monitor to set picture to \"$file\""
 }
